# Generated by Django 4.2.7 on 2023-11-15 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_del_area', models.CharField(max_length=200)),
                ('Descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Edad', models.PositiveIntegerField()),
                ('DUI', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=200)),
                ('Apellido', models.CharField(max_length=200)),
                ('Edad', models.PositiveIntegerField()),
                ('AreaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PosGre.area')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_Venta', models.DateTimeField()),
                ('Monto', models.FloatField(max_length=100)),
                ('Clienteid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PosGre.cliente')),
                ('EmpleadoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PosGre.empleado')),
            ],
        ),
    ]
